version: "3"

services:
  server:
    image: node:lts
    container_name: server
    tty: true
    expose:
      - 3000
      - 9229
    ports:
      - 5000:3000
      - 9229:9229
    volumes:
      - ./:/src
    working_dir: "/src/server"
    command: "npm run start:debug && sh -c 'npx tsc; npm run dev'"
    # Dockerコンテナ起動時にtsファイルをコンパイルしてからnodemon起動
  
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      TZ: ${TZ}
    ports:
        - ${DB_PORT}:3306
    volumes:
        - db-store:/var/lib/mysql
volumes:
  db-store: